(()=>{const cfg=window.FE_SECURITY_CONFIG||{};let pin=sessionStorage.getItem('feSecurityPin')||'',records=[];const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(action,payload={}){if(!cfg.API_URL||cfg.API_URL.includes('PASTE_'))throw new Error('Configure security-console/config.js with the Apps Script URL.');const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,pin,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d}
async function login(){pin=$('#pinInput').value.trim();try{await api('securityLogin');sessionStorage.setItem('feSecurityPin',pin);showApp();await load()}catch(e){$('#loginMsg').textContent=e.message}}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');$('#apiStatus').textContent='Connected';$('#apiStatus').classList.add('online') }
async function load(){const q=$('#searchInput').value.trim(),status=$('#statusFilter').value;const d=await api('listVisits',{query:q,status});records=d.visits||[];renderRows();renderKpis(d.kpis||{})}
function renderKpis(k){$('#kExpected').textContent=k.expectedToday||0;$('#kOnsite').textContent=k.onsite||0;$('#kOut').textContent=k.checkedOutToday||0;$('#kOverdue').textContent=k.overdue||0}
function renderRows(){const body=$('#visitorRows');body.innerHTML=records.map((r,i)=>`<tr><td><b>${esc(r.fullName)}</b><br><small>${esc(r.company)}</small></td><td>${esc(r.startDate)} ${esc(r.arrivalTime)}<br><small>${esc(r.confirmationNumber)}</small></td><td>${esc(r.sponsorName)}<br><small>${esc(r.department)}</small></td><td><span class="status ${esc((r.status||'').toLowerCase().replaceAll(' ','-'))}">${esc(r.status)}</span></td><td>${esc(r.badgeUid||'—')}</td><td><button class="row-btn" data-i="${i}">Open</button></td></tr>`).join('');$('#emptyState').classList.toggle('hidden',records.length>0);document.querySelectorAll('.row-btn').forEach(b=>b.onclick=()=>openRecord(records[Number(b.dataset.i)]))}
function openRecord(r){const checkedIn=r.status==='Checked In';$('#detailPanel').innerHTML=`<div class="detail-head"><img class="photo" src="${esc(r.photoUrl||'')}" alt="Visitor photo"><div><h2>${esc(r.fullName)}</h2><p>${esc(r.company)}</p><span class="status ${esc((r.status||'').toLowerCase().replaceAll(' ','-'))}">${esc(r.status)}</span></div></div><div class="detail-grid">${field('Confirmation',r.confirmationNumber)}${field('Sponsor',r.sponsorName)}${field('Department',r.department)}${field('Phone',r.phone)}${field('Visit period',`${r.startDate} ${r.arrivalTime} – ${r.endDate} ${r.departureTime}`)}${field('Access',r.accessScope)}${field('Reason',r.reason)}${field('Plate',r.licensePlate||'—')}${field('Check in',r.checkInTime||'—')}${field('Check out',r.checkOutTime||'—')}</div><div class="actions">${!checkedIn&&r.status!=='Checked Out'?`<label>Badge UID<input id="badgeUid" placeholder="Scan or enter badge UID"></label><label>Officer name<input id="officerName" placeholder="Security officer"></label><label>Sponsor notification notes<textarea id="checkNotes"></textarea></label><button id="checkInAction">Check In Visitor</button>`:''}${checkedIn?`<label>Returned badge UID<input id="returnBadgeUid" value="${esc(r.badgeUid||'')}"></label><label>Officer name<input id="outOfficerName" placeholder="Security officer"></label><label>Checkout notes<textarea id="outNotes"></textarea></label><button id="checkOutAction">Check Out Visitor</button>`:''}<button id="approveAction" class="secondary">Mark Approved</button><button id="noShowAction" class="danger">Mark No Show</button></div>`;
$('#checkInAction')?.addEventListener('click',()=>act('checkInVisit',r.visitId,{badgeUid:$('#badgeUid').value,officerName:$('#officerName').value,notes:$('#checkNotes').value,idRetained:true,sponsorNotified:true}));$('#checkOutAction')?.addEventListener('click',()=>act('checkOutVisit',r.visitId,{badgeUid:$('#returnBadgeUid').value,officerName:$('#outOfficerName').value,notes:$('#outNotes').value,idReturned:true}));$('#approveAction').onclick=()=>act('updateVisitStatus',r.visitId,{status:'Approved'});$('#noShowAction').onclick=()=>act('updateVisitStatus',r.visitId,{status:'No Show'});}
function field(k,v){return`<div class="field"><b>${esc(k)}</b>${esc(v||'—')}</div>`}
async function act(action,visitId,extra){try{await api(action,{visitId,...extra});await load();const updated=records.find(x=>x.visitId===visitId);if(updated)openRecord(updated)}catch(e){alert(e.message)}}
$('#loginBtn').onclick=login;$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#refreshBtn').onclick=load;$('#searchBtn').onclick=load;$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('#logoutBtn').onclick=()=>{sessionStorage.clear();location.reload()};if(pin){showApp();load().catch(()=>{sessionStorage.clear();location.reload()})}})();
