(()=>{
  const cfg=window.FE_ADMIN_CONFIG||{};
  let token=sessionStorage.getItem('feVistaToken')||'',user=null,permissions={},users=[],badges=[],currentReport=null,pendingPhotoDataUrl='',removePhoto=false,dialogPhotoRequest=0;
  const userPhotoCache=new Map(),userPhotoLoads=new Map();
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalizeBadgeUid=v=>String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');
  const roleAvatarClass=role=>{const k=String(role||'').toLowerCase().replace(/[^a-z]/g,'');if(k==='admin'||k==='superadministrator'||k==='superadmin')return'avatar-admin';if(k==='securitysupervisor')return'avatar-security-supervisor';if(k==='security'||k==='securityofficer'||k==='frontdesk')return'avatar-security';if(k==='sponsor')return'avatar-sponsor';if(k==='approver')return'avatar-approver';return'avatar-neutral'};
  async function api(action,payload={}){if(!cfg.API_URL)throw new Error('Administration API URL is not configured.');const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d}
  function toast(m){$('#toast').textContent=m;$('#toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.add('hidden'),3000)}
  async function completeLogin(action,payload){const msg=$('#loginMsg');msg.textContent='Signing in…';try{const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload:{...payload,userAgent:navigator.userAgent}})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Login failed');if(!d.permissions?.manageUsers){try{await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token:d.token,payload:{}})})}catch(_e){}throw new Error('This account is not authorized for VISTA Administration.');}token=d.token;user=d.user;permissions=d.permissions||{};sessionStorage.setItem('feVistaToken',token);sessionStorage.setItem('feVistaUser',JSON.stringify(user));sessionStorage.setItem('feVistaPermissions',JSON.stringify(permissions));msg.textContent='';show();await load()}catch(e){msg.textContent=e.message;if(action==='badgeLogin'){$('#loginBadgeUid').value='';$('#loginBadgeUid').focus()}}}
  async function pinLogin(){const username=$('#username').value.trim(),pin=$('#pin').value.trim();if(!username||!pin){$('#loginMsg').textContent='Enter your username and PIN.';return}await completeLogin('pinLogin',{username,pin})}
  async function badgeLogin(){const badgeUid=normalizeBadgeUid($('#loginBadgeUid').value);if(!badgeUid){$('#loginMsg').textContent='Scan or enter a Ford Energy badge UID.';return}await completeLogin('badgeLogin',{badgeUid})}
  function show(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');$('#sessionUser').textContent=`${user.fullName} · ${user.role}`;const avatar=$('#sessionAvatar');avatar.classList.remove('avatar-admin','avatar-security','avatar-security-supervisor','avatar-sponsor','avatar-approver','avatar-neutral');avatar.classList.add(roleAvatarClass(user.role));loadSessionAvatar()}
  async function load(){const d=await api('listUsers',{query:$('#search').value,role:$('#roleFilter').value,active:$('#activeFilter').value});const maxFailures=Number(d.summary.maxFailedLogins||5);users=(d.users||[]).map(u=>({...u,locked:Number(u.failedLoginCount||0)>=maxFailures}));$('#kTotal').textContent=d.summary.total;$('#kActive').textContent=d.summary.active;$('#kAdmins').textContent=d.summary.admins;$('#kDisabled').textContent=d.summary.disabled;$('#kLocked').textContent=d.summary.locked||0;$('#rows').innerHTML=users.map((u,i)=>`<tr><td><div class="user-cell"><div class="mini-avatar ${roleAvatarClass(u.role)} ${u.hasPhoto?'photo-pending':''}" data-user-photo="${esc(u.userId)}" aria-label="${esc(u.fullName)} profile photo"><span>${esc((u.fullName||'?').charAt(0))}</span></div><div><b>${esc(u.fullName)}</b><br><small>${esc(u.email||u.username)} · ${esc(u.employeeId||'No employee ID')}</small></div></div></td><td>${esc(u.role)}</td><td>${esc(u.department||'—')}</td><td>${esc(u.badgeUid||'—')}</td><td><span class="pill ${u.locked?'locked':u.active?'active':'disabled'}">${u.locked?'Locked':u.active?'Active':'Disabled'}</span>${u.locked?`<small class="failed-count">${esc(u.failedLoginCount)} failed attempts</small>`:''}</td><td><div class="actions"><button data-edit="${i}">Edit</button>${u.locked?`<button data-unlock="${i}" class="unlock">Unlock</button>`:''}<button data-toggle="${i}" class="secondary">${u.active?'Disable':'Enable'}</button><button data-pin="${i}" class="secondary">Reset PIN</button><button data-del="${i}" class="danger">Delete</button></div></td></tr>`).join('');$('#empty').classList.toggle('hidden',users.length>0);bindRows();loadUserThumbnails();await Promise.all([loadBadges(),loadAudit(),loadAnalytics()])}

  async function loadBadges(){const d=await api('listBadges',{query:$('#badgeSearch').value,status:$('#badgeStatusFilter').value});badges=d.badges;$('#bTotal').textContent=d.summary.total;$('#bAvailable').textContent=d.summary.available;$('#bIssued').textContent=d.summary.issued;$('#bUnavailable').textContent=d.summary.unavailable;$('#badgeRows').innerHTML=badges.map((b,i)=>`<tr><td><b>Visitor Badge ${esc(b.badgeNumber||'Unnumbered')}</b></td><td><code>${esc(b.badgeUid)}</code></td><td><span class="pill badge-${esc(b.status.toLowerCase())}">${esc(b.status)}</span></td><td>${esc(b.currentVisitId||'—')}</td><td>${esc(b.returnedAt||'—')}</td><td><div class="actions">${b.status==='Issued'?'<span class="issued-lock">Return in Security Operations</span>':`<button data-badge-edit="${i}">Edit</button>`}</div></td></tr>`).join('');$('#badgeEmpty').classList.toggle('hidden',badges.length>0);document.querySelectorAll('[data-badge-edit]').forEach(btn=>btn.onclick=()=>openBadge(badges[+btn.dataset.badgeEdit]))}
  function closeBadge(){if($('#badgeDialog').open)$('#badgeDialog').close();$('#badgeFormMsg').textContent=''}
  function openBadge(b={}){$('#badgeDialogTitle').textContent=b.badgeUid?'Edit Visitor Badge':'Add Visitor Badge';$('#badgeNumber').value=b.badgeNumber||'';$('#inventoryBadgeUid').value=b.badgeUid||'';$('#inventoryBadgeUid').readOnly=Boolean(b.badgeUid);$('#inventoryBadgeStatus').value=b.status&&b.status!=='Issued'?b.status:'Available';$('#badgeNotes').value=b.notes||'';$('#badgeFormMsg').textContent='';$('#badgeDialog').showModal();setTimeout(()=>$('#badgeNumber').focus(),50)}
  async function saveBadge(e){e.preventDefault();const button=$('#saveBadgeBtn');button.disabled=true;button.textContent='Saving…';$('#badgeFormMsg').textContent='';try{const d=await api('saveBadge',{badgeNumber:$('#badgeNumber').value,badgeUid:$('#inventoryBadgeUid').value,status:$('#inventoryBadgeStatus').value,notes:$('#badgeNotes').value});closeBadge();toast(d.message);await Promise.all([loadBadges(),loadAudit()])}catch(err){$('#badgeFormMsg').textContent=err.message}finally{button.disabled=false;button.textContent='Save Badge'}}

  function getCachedUserPhoto(userId){return userPhotoCache.get(String(userId||''))||''}
  async function fetchUserPhoto(userId){
    const key=String(userId||'');if(!key)return'';
    if(userPhotoCache.has(key))return userPhotoCache.get(key);
    if(userPhotoLoads.has(key))return userPhotoLoads.get(key);
    const job=api('getUserPhoto',{userId:key}).then(d=>{const src=d.hasPhoto&&d.dataUrl?d.dataUrl:'';userPhotoCache.set(key,src);return src}).catch(()=>{userPhotoCache.set(key,'');return''}).finally(()=>userPhotoLoads.delete(key));
    userPhotoLoads.set(key,job);return job;
  }
  function paintUserThumbnail(userId,src){document.querySelectorAll(`[data-user-photo="${CSS.escape(String(userId))}"]`).forEach(host=>{host.classList.remove('photo-pending');if(src){host.innerHTML=`<img src="${src}" alt="" loading="lazy">`;host.classList.add('has-photo')}else host.classList.remove('has-photo')})}
  function loadUserThumbnails(){
    users.filter(u=>u.hasPhoto).forEach(u=>{const cached=getCachedUserPhoto(u.userId);if(cached){paintUserThumbnail(u.userId,cached);return}fetchUserPhoto(u.userId).then(src=>paintUserThumbnail(u.userId,src))});
  }
  function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openUser(users[+b.dataset.edit]));document.querySelectorAll('[data-unlock]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.unlock];if(confirm(`Unlock ${u.fullName}? Their existing PIN will remain unchanged.`)){const d=await api('unlockUser',{userId:u.userId});toast(d.message||'Account unlocked.');await load()}});document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.toggle];if(confirm(`${u.active?'Disable':'Enable'} ${u.fullName}?`)){await api('setUserActive',{userId:u.userId,active:!u.active});toast('Account status updated.');load()}});document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.pin],pin=prompt(`Enter a new PIN for ${u.fullName}:`);if(pin){await api('resetUserPin',{userId:u.userId,pin});toast('PIN reset and account unlocked.');await load()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.del];if(confirm(`Permanently delete ${u.fullName}?`)){await api('deleteUser',{userId:u.userId});toast('User deleted.');load()}})}
  function closeUserDialog(){dialogPhotoRequest++;pendingPhotoDataUrl='';removePhoto=false;$('#formMsg').textContent='';$('#saveBtn').disabled=false;$('#saveBtn').textContent='Save User';if($('#userDialog').open)$('#userDialog').close()}
  function openUser(u={}){dialogPhotoRequest++;const requestId=dialogPhotoRequest;pendingPhotoDataUrl='';removePhoto=false;$('#userPhoto').value='';setPhotoPreview('');$('#removePhotoBtn').classList.toggle('hidden',!u.hasPhoto);if(u.hasPhoto)loadUserPhoto(u.userId,requestId);$('#dialogTitle').textContent=u.userId?'Edit User':'Add User';$('#userId').value=u.userId||'';$('#fullName').value=u.fullName||'';$('#employeeId').value=u.employeeId||'';$('#email').value=u.email||'';$('#userName').value=u.username||'';$('#role').value=u.role||'Security';$('#department').value=u.department||'';$('#company').value=u.company||'Ford Energy';$('#badgeUid').value=u.badgeUid||'';$('#newPin').value='';$('#notes').value=u.notes||'';$('#active').checked=u.active!==false;$('#formMsg').textContent='';$('#saveBtn').disabled=false;$('#saveBtn').textContent='Save User';$('#userDialog').showModal()}
  async function save(e){e.preventDefault();const saveBtn=$('#saveBtn'),editingId=$('#userId').value;saveBtn.disabled=true;saveBtn.textContent=pendingPhotoDataUrl?'Saving photo…':'Saving user…';$('#formMsg').textContent='';try{const result=await api('saveUser',{userId:editingId,fullName:$('#fullName').value,employeeId:$('#employeeId').value,email:$('#email').value,username:$('#userName').value,role:$('#role').value,department:$('#department').value,company:$('#company').value,badgeUid:$('#badgeUid').value,photoDataUrl:pendingPhotoDataUrl,removePhoto,pin:$('#newPin').value,notes:$('#notes').value,active:$('#active').checked});userPhotoCache.delete(String(editingId||result.user?.userId||''));if(result.user&&String(result.user.userId)===String(user?.userId)){user={...user,...result.user};sessionStorage.setItem('feVistaUser',JSON.stringify(user));show()}closeUserDialog();toast(result.message||'User saved.');await load()}catch(err){$('#formMsg').textContent=err.message;saveBtn.disabled=false;saveBtn.textContent='Save User'}}
  function setPhotoPreview(src){const img=$('#userPhotoPreview'),ph=$('#userPhotoPlaceholder');if(src){img.src=src;img.classList.remove('hidden');ph.classList.add('hidden')}else{img.removeAttribute('src');img.classList.add('hidden');ph.classList.remove('hidden')}}
  async function imageToDataUrl(file){if(!file)return'';if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw new Error('Select a JPG, PNG, or WebP image.');return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.86))}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('The selected image could not be read.'))};img.src=url})}
  async function loadUserPhoto(userId,requestId){const src=await fetchUserPhoto(userId);if(requestId!==dialogPhotoRequest||!$('#userDialog').open)return;if(src)setPhotoPreview(src)}
  async function loadSessionAvatar(){try{const key=String(user?.userId||'self'),img=$('#sessionAvatar');let src=getCachedUserPhoto(key);if(!src){const d=await api('getUserPhoto',{});src=d.hasPhoto&&d.dataUrl?d.dataUrl:'';userPhotoCache.set(key,src)}if(src){img.src=src;img.classList.remove('hidden')}else img.classList.add('hidden')}catch(e){}}
  function minutesLabel(value){const n=Math.max(0,Number(value||0)),h=Math.floor(n/60),m=n%60;return h?`${h}h ${m}m`:`${m}m`}
  function barRows(items){const max=Math.max(1,...items.map(x=>Number(x.count||0)));return items.length?items.map(x=>`<div class="bar-row"><span title="${esc(x.label)}">${esc(x.label)}</span><span class="bar-track"><i class="bar-fill" style="width:${Math.round(Number(x.count||0)/max*100)}%"></i></span><strong>${Number(x.count||0)}</strong></div>`).join(''):'<p class="analytics-empty">No activity in this period.</p>'}
  function compressDaily(rows){const source=rows||[],size=Math.max(1,Math.ceil(source.length/31)),result=[];for(let i=0;i<source.length;i+=size){const part=source.slice(i,i+size);result.push({date:part[0]?.date||'',end:part.at(-1)?.date||'',count:part.reduce((sum,x)=>sum+Number(x.count||0),0)})}return result}
  async function loadAnalytics(){const panel=$('.analytics-panel'),button=$('#analyticsRefresh'),error=$('#analyticsError');panel.classList.add('analytics-loading');button.disabled=true;error.classList.add('hidden');try{const d=await api('getOperationalAnalytics',{days:Number($('#analyticsRange').value||30)}),summary=d.summary||{},handoffs=d.handoffs||{},badge=d.badges||{};$('#analyticsGenerated').textContent=`${d.range.start} through ${d.range.end} · Updated ${d.generatedAt}`;$('#anVisits').textContent=summary.totalVisits||0;$('#anApproval').textContent=`${summary.approvalRate||0}%`;$('#anOnsite').textContent=summary.onsiteNow||0;$('#anDuration').textContent=minutesLabel(summary.averageDurationMinutes);$('#anPeak').textContent=summary.peakArrivalHour||'—';$('#anEscalated').textContent=handoffs.escalated||0;const statusOrder=['Submitted','Approved','Checked In','Checked Out','Denied','No Show'];$('#statusChart').innerHTML=barRows(statusOrder.map(label=>({label,count:d.statuses?.[label]||0})));$('#sponsorChart').innerHTML=barRows((d.topSponsors||[]).map(x=>({label:x.name,count:x.count})));const daily=compressDaily(d.dailyVolume),max=Math.max(1,...daily.map(x=>x.count));$('#dailyChart').innerHTML=daily.map(x=>{const height=Math.max(2,Math.round(x.count/max*100)),label=x.date===x.end?`${x.date}: ${x.count}`:`${x.date} – ${x.end}: ${x.count}`;return `<span class="column" data-label="${esc(label)}" style="--height:${height}%"><i style="height:${height}%"></i></span>`}).join('')||'<p class="analytics-empty">No visit volume in this period.</p>';$('#operationsHealth').innerHTML=`<div class="health-item"><span>Available Badges</span><b>${badge.available||0} / ${badge.total||0}</b></div><div class="health-item ${badge.unavailable?'attention':''}"><span>Unavailable Badges</span><b>${badge.unavailable||0}</b></div><div class="health-item"><span>Pending Handoffs</span><b>${handoffs.pending||0}</b></div><div class="health-item"><span>Acknowledged</span><b>${handoffs.acknowledged||0}</b></div><div class="health-item"><span>Resolved</span><b>${handoffs.resolved||0}</b></div><div class="health-item ${handoffs.escalated?'attention':''}"><span>Supervisor Escalations</span><b>${handoffs.escalated||0}</b></div><div class="health-item"><span>Avg. Acknowledgement</span><b>${minutesLabel(handoffs.averageAcknowledgementMinutes)}</b></div><div class="health-item"><span>Avg. Resolution</span><b>${minutesLabel(handoffs.averageResolutionMinutes)}</b></div>`}catch(e){error.textContent='Analytics unavailable: '+e.message;error.classList.remove('hidden')}finally{panel.classList.remove('analytics-loading');button.disabled=false}}
  async function generateReport(){const panel=$('.reporting-panel'),button=$('#generateReport'),error=$('#reportError');panel.classList.add('reporting-loading');button.disabled=true;button.textContent='Generating…';error.classList.add('hidden');try{currentReport=await api('generateOperationalReport',{reportType:$('#reportType').value,days:Number($('#reportRange').value||30),query:$('#reportQuery').value.trim()});renderReport(currentReport);$('#reportPreview').classList.remove('hidden');toast(`${currentReport.title} generated.`)}catch(e){currentReport=null;$('#reportPreview').classList.add('hidden');error.textContent=e.message;error.classList.remove('hidden')}finally{panel.classList.remove('reporting-loading');button.disabled=false;button.textContent='Generate Preview'}}
  function renderReport(report){$('#reportTitle').textContent=report.title;$('#reportMeta').textContent=`${report.range.start} through ${report.range.end} · Generated ${report.generatedAt}`;$('#reportHead').innerHTML=`<tr>${report.columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr>`;$('#reportRows').innerHTML=report.rows.length?report.rows.map(row=>`<tr>${report.columns.map(c=>`<td>${esc(row[c.key]??'')}</td>`).join('')}</tr>`).join(''):`<tr><td class="report-empty" colspan="${report.columns.length}">No records matched this report.</td></tr>`;$('#reportFoot').textContent=`${report.totalRows} record${report.totalRows===1?'':'s'}${report.truncated?' · Preview limited to the first 1,000 records':''} · Generated by ${user?.fullName||user?.username||'VISTA Administrator'}`}
  function safeCsvValue(value){let text=String(value??'');if(/^[=+\-@]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"'}
  async function exportReportCsv(){if(!currentReport){toast('Generate a report before exporting.');return}await api('recordReportExport',{reportType:currentReport.reportType,format:'CSV',rowCount:currentReport.rows.length});const lines=[currentReport.columns.map(c=>safeCsvValue(c.label)).join(','),...currentReport.rows.map(row=>currentReport.columns.map(c=>safeCsvValue(row[c.key])).join(','))],blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a'),stamp=new Date().toISOString().slice(0,10);link.href=url;link.download=`VISTA-${currentReport.reportType}-${stamp}.csv`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('CSV report exported.')}
  async function printCurrentReport(){if(!currentReport){toast('Generate a report before printing.');return}await api('recordReportExport',{reportType:currentReport.reportType,format:'PRINT',rowCount:currentReport.rows.length});document.body.classList.add('report-printing');const cleanup=()=>document.body.classList.remove('report-printing');window.addEventListener('afterprint',cleanup,{once:true});window.print();setTimeout(cleanup,1500)}
  async function loadAudit(){try{const d=await api('listAudit',{limit:15,query:'ADMIN_'});$('#auditRows').innerHTML=d.events.map(x=>`<div class="audit-item"><span>${esc(x.timestamp)}</span><b>${esc(x.username)}</b><span>${esc(x.action)} · ${esc(x.details)}</span><span>${esc(x.result)}</span></div>`).join('')||'<p>No administration activity yet.</p>'}catch(e){$('#auditRows').innerHTML='<p>Audit log unavailable.</p>'}}
  $('#loginBtn').onclick=pinLogin;$('#badgeLoginBtn').onclick=badgeLogin;
  window.addEventListener('vista:nfc-scan',event=>{const uid=normalizeBadgeUid(event.detail?.uid||'');if(!uid)return;if(!token){$('#loginBadgeUid').value=uid;badgeLogin();return}const inventory=$('#inventoryBadgeUid'),userBadge=$('#badgeUid');if($('#badgeDialog').open&&inventory){inventory.value=uid;inventory.focus();toast('NFC badge UID captured.')}else if($('#userDialog').open&&userBadge){userBadge.value=uid;userBadge.focus();toast('NFC badge UID captured.')}else toast('NFC badge read. Open a user or badge record to assign it.')});
  $('#pin').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();pinLogin()}});$('#loginBadgeUid').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();badgeLogin()}});
  $('#showPinLoginBtn').onclick=()=>{$('#badgeLoginPanel').classList.add('hidden');$('#pinLoginPanel').classList.remove('hidden');$('#showPinLoginBtn').classList.add('hidden');$('#username').focus()};
  $('#showBadgeLoginBtn').onclick=()=>{$('#pinLoginPanel').classList.add('hidden');$('#badgeLoginPanel').classList.remove('hidden');$('#showPinLoginBtn').classList.remove('hidden');$('#loginBadgeUid').focus()};
  $('#addBtn').onclick=()=>openUser();$('#userForm').onsubmit=save;$('#userDialogClose').onclick=closeUserDialog;$('#userDialogCancel').onclick=closeUserDialog;$('#userDialog').addEventListener('cancel',e=>{e.preventDefault();closeUserDialog()});$('#userDialog').addEventListener('click',e=>{if(e.target===$('#userDialog'))closeUserDialog()});$('#refreshBtn').onclick=load;$('#auditRefresh').onclick=loadAudit;$('#analyticsRefresh').onclick=loadAnalytics;$('#analyticsRange').onchange=loadAnalytics;$('#generateReport').onclick=generateReport;$('#exportCsv').onclick=()=>exportReportCsv().catch(e=>toast(e.message));$('#printReport').onclick=()=>printCurrentReport().catch(e=>toast(e.message));$('#reportQuery').onkeydown=e=>{if(e.key==='Enter')generateReport()};$('#search').onkeydown=e=>{if(e.key==='Enter')load()};$('#roleFilter').onchange=load;$('#activeFilter').onchange=load;
  $('#addBadgeBtn').onclick=()=>openBadge();$('#badgeForm').onsubmit=saveBadge;$('#badgeDialogClose').onclick=closeBadge;$('#badgeDialogCancel').onclick=closeBadge;$('#badgeDialog').addEventListener('cancel',e=>{e.preventDefault();closeBadge()});$('#badgeDialog').addEventListener('click',e=>{if(e.target===$('#badgeDialog'))closeBadge()});$('#badgeRefresh').onclick=loadBadges;$('#badgeStatusFilter').onchange=loadBadges;$('#badgeSearch').onkeydown=e=>{if(e.key==='Enter')loadBadges()};
  $('#userPhoto').onchange=async e=>{try{pendingPhotoDataUrl=await imageToDataUrl(e.target.files[0]);removePhoto=false;setPhotoPreview(pendingPhotoDataUrl);$('#removePhotoBtn').classList.remove('hidden');$('#formMsg').textContent=''}catch(err){$('#formMsg').textContent=err.message;e.target.value=''}};
  $('#removePhotoBtn').onclick=()=>{pendingPhotoDataUrl='';removePhoto=true;$('#userPhoto').value='';setPhotoPreview('');$('#removePhotoBtn').classList.add('hidden')};
  $('#logoutBtn').onclick=async()=>{try{await api('logout')}catch(e){}sessionStorage.clear();location.reload()};
  if(!token)setTimeout(()=>$('#loginBadgeUid')?.focus(),100);
  if(token){try{user=JSON.parse(sessionStorage.getItem('feVistaUser')||'null');permissions=JSON.parse(sessionStorage.getItem('feVistaPermissions')||'{}');if(!user||!permissions.manageUsers)throw new Error('Unauthorized');show();load().catch(()=>{sessionStorage.clear();location.reload()})}catch(e){sessionStorage.clear()}}
})();
