(()=>{
  const cfg=window.FE_ADMIN_CONFIG||{};
  let token=sessionStorage.getItem('feVistaToken')||'',user=null,permissions={},users=[],pendingPhotoDataUrl='',removePhoto=false;
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalizeBadgeUid=v=>String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');
  async function api(action,payload={}){if(!cfg.API_URL)throw new Error('Administration API URL is not configured.');const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed');return d}
  function toast(m){$('#toast').textContent=m;$('#toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.add('hidden'),3000)}
  async function completeLogin(action,payload){const msg=$('#loginMsg');msg.textContent='Signing in…';try{const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload:{...payload,userAgent:navigator.userAgent}})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Login failed');if(!d.permissions?.manageUsers){try{await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'logout',token:d.token,payload:{}})})}catch(_e){}throw new Error('This account is not authorized for VISTA Administration.');}token=d.token;user=d.user;permissions=d.permissions||{};sessionStorage.setItem('feVistaToken',token);sessionStorage.setItem('feVistaUser',JSON.stringify(user));sessionStorage.setItem('feVistaPermissions',JSON.stringify(permissions));msg.textContent='';show();await load()}catch(e){msg.textContent=e.message;if(action==='badgeLogin'){$('#loginBadgeUid').value='';$('#loginBadgeUid').focus()}}}
  async function pinLogin(){const username=$('#username').value.trim(),pin=$('#pin').value.trim();if(!username||!pin){$('#loginMsg').textContent='Enter your username and PIN.';return}await completeLogin('pinLogin',{username,pin})}
  async function badgeLogin(){const badgeUid=normalizeBadgeUid($('#loginBadgeUid').value);if(!badgeUid){$('#loginMsg').textContent='Scan or enter a Ford Energy badge UID.';return}await completeLogin('badgeLogin',{badgeUid})}
  function show(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#logoutBtn').classList.remove('hidden');$('#sessionUser').textContent=`${user.fullName} · ${user.role}`;loadSessionAvatar()}
  async function load(){const d=await api('listUsers',{query:$('#search').value,role:$('#roleFilter').value,active:$('#activeFilter').value});users=d.users;$('#kTotal').textContent=d.summary.total;$('#kActive').textContent=d.summary.active;$('#kAdmins').textContent=d.summary.admins;$('#kDisabled').textContent=d.summary.disabled;$('#rows').innerHTML=users.map((u,i)=>`<tr><td><div class="user-cell"><div class="mini-avatar">${esc((u.fullName||'?').charAt(0))}</div><div><b>${esc(u.fullName)}</b><br><small>${esc(u.email||u.username)} · ${esc(u.employeeId||'No employee ID')}</small></div></div></td><td>${esc(u.role)}</td><td>${esc(u.department||'—')}</td><td>${esc(u.badgeUid||'—')}</td><td><span class="pill ${u.active?'active':'disabled'}">${u.active?'Active':'Disabled'}</span></td><td><div class="actions"><button data-edit="${i}">Edit</button><button data-toggle="${i}" class="secondary">${u.active?'Disable':'Enable'}</button><button data-pin="${i}" class="secondary">Reset PIN</button><button data-del="${i}" class="danger">Delete</button></div></td></tr>`).join('');$('#empty').classList.toggle('hidden',users.length>0);bindRows();await loadAudit()}
  function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openUser(users[+b.dataset.edit]));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.toggle];if(confirm(`${u.active?'Disable':'Enable'} ${u.fullName}?`)){await api('setUserActive',{userId:u.userId,active:!u.active});toast('Account status updated.');load()}});document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.pin],pin=prompt(`Enter a new PIN for ${u.fullName}:`);if(pin){await api('resetUserPin',{userId:u.userId,pin});toast('PIN reset.')}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const u=users[+b.dataset.del];if(confirm(`Permanently delete ${u.fullName}?`)){await api('deleteUser',{userId:u.userId});toast('User deleted.');load()}})}
  function openUser(u={}){pendingPhotoDataUrl='';removePhoto=false;$('#userPhoto').value='';setPhotoPreview('');$('#removePhotoBtn').classList.toggle('hidden',!u.hasPhoto);if(u.hasPhoto)loadUserPhoto(u.userId);$('#dialogTitle').textContent=u.userId?'Edit User':'Add User';$('#userId').value=u.userId||'';$('#fullName').value=u.fullName||'';$('#employeeId').value=u.employeeId||'';$('#email').value=u.email||'';$('#userName').value=u.username||'';$('#role').value=u.role||'Security';$('#department').value=u.department||'';$('#company').value=u.company||'Ford Energy';$('#badgeUid').value=u.badgeUid||'';$('#newPin').value='';$('#notes').value=u.notes||'';$('#active').checked=u.active!==false;$('#formMsg').textContent='';$('#userDialog').showModal()}
  async function save(e){e.preventDefault();try{await api('saveUser',{userId:$('#userId').value,fullName:$('#fullName').value,employeeId:$('#employeeId').value,email:$('#email').value,username:$('#userName').value,role:$('#role').value,department:$('#department').value,company:$('#company').value,badgeUid:$('#badgeUid').value,photoDataUrl:pendingPhotoDataUrl,removePhoto,pin:$('#newPin').value,notes:$('#notes').value,active:$('#active').checked});$('#userDialog').close();toast('User saved.');load()}catch(e){$('#formMsg').textContent=e.message}}
  function setPhotoPreview(src){const img=$('#userPhotoPreview'),ph=$('#userPhotoPlaceholder');if(src){img.src=src;img.classList.remove('hidden');ph.classList.add('hidden')}else{img.removeAttribute('src');img.classList.add('hidden');ph.classList.remove('hidden')}}
  async function imageToDataUrl(file){if(!file)return'';if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw new Error('Select a JPG, PNG, or WebP image.');return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.86))}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('The selected image could not be read.'))};img.src=url})}
  async function loadUserPhoto(userId){try{const d=await api('getUserPhoto',{userId});if(d.hasPhoto)setPhotoPreview(d.dataUrl)}catch(e){}}
  async function loadSessionAvatar(){try{const d=await api('getUserPhoto',{}),img=$('#sessionAvatar');if(d.hasPhoto){img.src=d.dataUrl;img.classList.remove('hidden')}else img.classList.add('hidden')}catch(e){}}
  async function loadAudit(){try{const d=await api('listAudit',{limit:15,query:'ADMIN_'});$('#auditRows').innerHTML=d.events.map(x=>`<div class="audit-item"><span>${esc(x.timestamp)}</span><b>${esc(x.username)}</b><span>${esc(x.action)} · ${esc(x.details)}</span><span>${esc(x.result)}</span></div>`).join('')||'<p>No administration activity yet.</p>'}catch(e){$('#auditRows').innerHTML='<p>Audit log unavailable.</p>'}}
  $('#loginBtn').onclick=pinLogin;$('#badgeLoginBtn').onclick=badgeLogin;
  $('#pin').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();pinLogin()}});$('#loginBadgeUid').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();badgeLogin()}});
  $('#showPinLoginBtn').onclick=()=>{$('#badgeLoginPanel').classList.add('hidden');$('#pinLoginPanel').classList.remove('hidden');$('#showPinLoginBtn').classList.add('hidden');$('#username').focus()};
  $('#showBadgeLoginBtn').onclick=()=>{$('#pinLoginPanel').classList.add('hidden');$('#badgeLoginPanel').classList.remove('hidden');$('#showPinLoginBtn').classList.remove('hidden');$('#loginBadgeUid').focus()};
  $('#addBtn').onclick=()=>openUser();$('#userForm').onsubmit=save;$('#refreshBtn').onclick=load;$('#auditRefresh').onclick=loadAudit;$('#search').onkeydown=e=>{if(e.key==='Enter')load()};$('#roleFilter').onchange=load;$('#activeFilter').onchange=load;
  $('#userPhoto').onchange=async e=>{try{pendingPhotoDataUrl=await imageToDataUrl(e.target.files[0]);removePhoto=false;setPhotoPreview(pendingPhotoDataUrl);$('#removePhotoBtn').classList.remove('hidden');$('#formMsg').textContent=''}catch(err){$('#formMsg').textContent=err.message;e.target.value=''}};
  $('#removePhotoBtn').onclick=()=>{pendingPhotoDataUrl='';removePhoto=true;$('#userPhoto').value='';setPhotoPreview('');$('#removePhotoBtn').classList.add('hidden')};
  $('#logoutBtn').onclick=async()=>{try{await api('logout')}catch(e){}sessionStorage.clear();location.reload()};
  if(!token)setTimeout(()=>$('#loginBadgeUid')?.focus(),100);
  if(token){try{user=JSON.parse(sessionStorage.getItem('feVistaUser')||'null');permissions=JSON.parse(sessionStorage.getItem('feVistaPermissions')||'{}');if(!user||!permissions.manageUsers)throw new Error('Unauthorized');show();load().catch(()=>{sessionStorage.clear();location.reload()})}catch(e){sessionStorage.clear()}}
})();